<?php

$request = $this->getRequest();
$module = $request->getModuleName() .'_'. $request->getControllerName() .'_'. $request->getActionName();
$resource = Mage::getSingleton('core/resource');
$read= $resource->getConnection('core_read');
$mmnTable = $resource->getTableName('mmn');

$select = $read->select()
						->distinct()
						->from($mmnTable,array('manufacturer','model','number'))
						->where('manufacturer != ?','')
						->where('model != ?','')
						->where('model != ?','')
						->order(array('manufacturer', 'model', 'number')) ;
   
$rows = $read->fetchAll($select);
			
if (count($rows) > 0) {
  
	$Manufacturer_array[] = array('id' => 'all', 'text' => $this->__('Choose Manufacturer'));
	$Model_array[] = array('id' => 'all', 'text' => $this->__('Choose Model'));
	$Number_array[] = array('id' => 'all', 'text' => $this->__('Choose Number'));

   $javascript = '<script type="text/javascript">
//<![CDATA[

var a = new Array();
var b = new Array();
var c = new Array();';

	$M_a = array();

	foreach ($rows as $r) {
			
			if (!isset($M_a [$r['manufacturer']]))
				$Manufacturer_array[] = array('id' => $r['manufacturer'], 'text' => $r['manufacturer']);
				
			$M_a [$r['manufacturer']][$r['model']][$r['number']] = 1;
	}		

		
	$i = 0;	
	foreach ($M_a as $k =>$v){
		$javascript .= 'a['.$i.']="'.$k.'";b['.$i.']=new Array(';
			$ii = 0;
			$s = '';
			foreach ($M_a[$k] as $kk =>$vv){
				$javascript .= ($ii != 0 ? ',' : '').'"'.$kk.'"';
				$ss = '';
				$iii = 0;
				foreach ($M_a[$k][$kk] as $kkk => $vvv){
					$ss .= ($iii != 0 ? ',' : '').'"'.$kkk.'"';
					$iii++;
				}
				$s .= 'c['.$i.']['.$ii.']=new Array('.$ss.');';
				$ii++;	
			}
		$javascript .= ');c['.$i.']=new Array();'.$s;	
		$i++;	
	}	
	
      $javascript .= '
function pop_model(){
	
	var o ="<select name=\"Model\" id=\"mmn_model\" onchange=\"pop_number();\" style=\"width: 100%\"><option value=\"all\">' . $this->__('Choose Model') . '</option>";	
	var sv = $(\'mmn_manufacturer\').value;
	if(sv != "all"){
		var v = a.length;
		while(v--) if(sv == a[v]) break;
		for(var i = 0; i < b[v].length; i++)
		  o+="<option value=\""+b[v][i]+"\">"+b[v][i]+"</option>";
	}
	o+="</select>";
	$(\'model_select\').innerHTML= o;
    $(\'number_select\').innerHTML= "<select name=\"Number\" style=\"width: 100%\"><option value=\"all\">' . $this->__('Choose Number') . '</option></select>";
}
function pop_number(){
	
	var o ="<select name=\"Number\" style=\"width: 100%\" onchange=\"$(\'mmn_form\').submit();\"><option value=\"all\">' . $this->__('Choose Number') . '</option>";
	var sv = $(\'mmn_manufacturer\').value;
	if(sv != "all"){
		var v = a.length;
		while(v--) if(sv == a[v]) break;
		var sv2 = $(\'mmn_model\').value;
			if(sv2 != "all"){
				var v2 = b[v].length;
				while(v2--) if(sv2 == b[v][v2]) break;	
				for(var i = 0; i < c[v][v2].length; i++)
					o+="<option value=\""+c[v][v2][i]+"\">"+c[v][v2][i]+"</option>";
			}
	}
	o+="</select>";
	$(\'number_select\').innerHTML= o;
}
//]]>
</script>';

	$expire = time()+60*60*24*90;
	
	if (isset($_GET['Manufacturer'])){
		setcookie("Manufacturer_selected", $_GET['Manufacturer'], $expire,'/');
		if ($_GET['Manufacturer'] != 'all')
			$Manufacturer_selected_var = $_GET['Manufacturer'];
	} elseif (isset($_COOKIE['Manufacturer_selected']) && $_COOKIE['Manufacturer_selected'] != 'all')	
		$Manufacturer_selected_var = $_COOKIE['Manufacturer_selected'];
		
	if (isset($_GET['Model'])){
		setcookie("Model_selected", $_GET['Model'], $expire,'/'); 
		if ($_GET['Model'] != 'all')
			$Model_selected_var = $_GET['Model'];
	} elseif (isset($_COOKIE['Model_selected']) && $_COOKIE['Model_selected'] != 'all')
		$Model_selected_var = $_COOKIE['Model_selected'];
		
	if (isset($_GET['Number'])){
		setcookie("Number_selected", $_GET['Number'], $expire,'/');
		if ($_GET['Number'] != 'all')
			$Number_selected_var = $_GET['Number'];
	} elseif (isset($_COOKIE['Number_selected']) && $_COOKIE['Number_selected'] != 'all')
		$Number_selected_var = $_COOKIE['Number_selected'];

    if (isset($Manufacturer_selected_var) && isset($M_a[$Manufacturer_selected_var]))
      foreach ($M_a[$Manufacturer_selected_var] as $k => $v)
		$Model_array[] = array('id' => $k, 'text' => $k);
	if (isset($Manufacturer_selected_var) && isset($Model_selected_var) && isset($M_a[$Manufacturer_selected_var][$Model_selected_var]))
      foreach ($M_a[$Manufacturer_selected_var][$Model_selected_var] as $k => $v)
		$Number_array[] = array('id' => $k, 'text' => $k);
		
	echo $javascript;
	
?>
<div class="box base-mini mini-poll">
    <div class="head">
        <h4><span><?php echo $this->__('Select Printer'); ?></span></h4>
    </div>
    <form id="mmn_form"  action="<?php 
	$hidden = '';
	if($module == 'catalog_category_view'){
		echo '';
	} elseif ($module == 'catalogsearch_result_index' && Mage::getStoreConfig('catalog/search/filtering', Mage::app()->getStore()->getStoreId())){
		$hidden = '<input type="hidden" name="q" value="' . $request->getParam('q')  . '">';
	}	else {
		echo Mage::getUrl('mmn/product/list');
	}	

?>" method="get" onsubmit="return $('mmn_manufacturer').value != 'all' ? true : false">
<?php echo $hidden; ?>
        <div class="content">
			<select name="Manufacturer" id="mmn_manufacturer" onchange="pop_model();"  style="width: 100%">
			<?php
			foreach($Manufacturer_array as $option)
				echo '<option value="'.$option['id'].'" '.(isset($Manufacturer_selected_var) && $Manufacturer_selected_var == $option['id'] ? 'SELECTED' : '').'>'.$option['text'].'</option>';
			?>
			</select><br/><br/>
			<span id="model_select">
			<select name="Model" id="mmn_model" onchange="pop_number();" style="width: 100%">
			<?php
			foreach($Model_array as $option)
				echo '<option value="'.$option['id'].'" '.(isset($Model_selected_var) && $Model_selected_var == $option['id'] ? 'SELECTED' : '').'>'.$option['text'].'</option>';
			?>
			</select></span><br/><br/>
			<span id="number_select">
			<select name="Number" onchange="$('mmn_form').submit();"  style="width: 100%">
			<?php
			foreach($Number_array as $option)
				echo '<option value="'.$option['id'].'" '.(isset($Number_selected_var) && $Number_selected_var == $option['id'] ? 'SELECTED' : '').'>'.$option['text'].'</option>';
			?>
			</select></span><br/><br/>			
        </div>
        <div class="actions">
		<button class="form-button-alt right" type="submit"><span><?php echo $this->__('Go'); ?></span></button>
		<?php if(isset($Manufacturer_selected_var)): ?>
			<a href="<?php 	
				if($module == 'catalog_category_view'){
					echo '?';
				} elseif ($module == 'catalogsearch_result_index' && Mage::getStoreConfig('catalog/search/filtering', Mage::app()->getStore()->getStoreId())){
					echo '?q=' . $request->getParam('q') . '&';
				}	else {
					echo Mage::getBaseUrl() . '?';
				}	
			?>Manufacturer=all&Model=all&Number=all"><?php echo $this->__('Clear Printer'); ?></a>&nbsp;&nbsp;&nbsp;&nbsp;
		<?php endif ?>
		</div>
    </form>
</div>	
<?php
}
?>
